import './globals.css';
import type { Metadata } from 'next';
import { Pretendard } from './font';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo'
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={Pretendard.variable}>{children}</body>
    </html>
  );
}
